#ifndef CRCONFIG_H
#define CRCONFIG_H

#define TXT_SMART_HEADERS false
#define TXT_SMART_DESCRIPTION false
#define FIRSTPAGE_BLOCKS_MAX 250
#define FIRSTPAGE_BLOCKS_MAX_WORD 4000
#define FIRSTPAGE_BLOCKS_MAX_RTF 3000
#define FIRSTPAGE_BLOCKS_MAX_CHM 5

#endif //CRCONFIG_H